
hostnossl    iot    iot_dba     127.0.0.1/32     trust
hostnossl    iot    iot_dba     172.19.0.1/32    trust
local   all         all                              trust
local   replication iot_dba                          trust
host    replication iot_dba     127.0.0.1/32         trust
hostssl all all 172.19.0.1/16 scram-sha-256
hostssl all all 127.0.0.1/32 scram-sha-256