listen_addresses = '*'

ssl = on
ssl_cert_file = '/etc/postgresql/ssl/server.crt'
ssl_key_file = '/etc/postgresql/ssl/server.key'

password_encryption = scram-sha-256

dynamic_shared_memory_type = posix

wal_level = replica
archive_mode = on   
archive_command = '/usr/local/bin/archive_wal.sh %f %p' #%p — путь к WAL в pg_wal
                                                        #%f — имя файла

